name: explode
description: "Explode Module"
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  module:
    androidX: true
    androidPackage: com.snstudio.hyper.explode
    iosBundleIdentifier: com.snstudio.hyper.explode
